// General
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const FETCH_INITIAL_CONFIG = 'FETCH_INITIAL_CONFIG';
export const SAVE_DATA = 'SAVE_DATA';


// Canvas
export const CANVAS_ITEM_UPDATE = 'CANVAS_ITEM_UPDATE';
export const CANVAS_ITEM_SELECTED = 'CANVAS_ITEM_SELECTED';
export const CANVAS_ITEM_DESELECTED = 'CANVAS_ITEM_DESELECTED';
export const CANVAS_ITEM_ADD = 'CANVAS_ITEM_ADD';
export const CANVAS_ITEM_REMOVE = 'CANVAS_ITEM_REMOVE';


// Floors
export const FLOOR_ADD = 'FLOOR_ADD';
export const FLOOR_REMOVE = 'FLOOR_REMOVE';
export const FLOOR_CHANGE = 'FLOOR_CHANGE';